spring:
    application:
        name: HospitalStaffManagement
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/graduation?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 19990821
server:
    port: 80
    servlet:
        context-path: /

mybatis:
    mapper-locations: classpath:com/lcw/mapper/*.xml
    type-aliases-package: com.lcw.graduation.entity

logging:
    level:
        root: info
        com.lcw.graduation.dao: debug
